name: notion_task_app
description: "A notion_task_app project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

assets:
  - .env

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_riverpod:
  freezed_annotation:
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true